brew "tmux"
brew "gnupg"
brew "pinentry-mac"
brew "mise"
brew "fzf"
brew "gh"
brew "shellcheck"
brew "hugo"
brew "docker"
brew "docker-compose"
brew "docker-buildx"
brew "colima"
brew "mas"
cask "font-meslo-lg-nerd-font"
cask "copyq"
cask "wezterm"
cask "visual-studio-code"
mas "Xcode", id: 497799835
