#+TITLE: My Emacs Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el
#+STARTUP: overview

* Introduction

  put ~#+PROPERTY: header-args:emacs-lisp :tangle ./init-new.el~ at the top of your ~org~ file, then after running ~org-babel-tangle (C-c C-v t)~ (this can be [[*Tangle Config Files][automated]] -- to be executed on save), the lisp blocks will be written to your ~init-new.el~ file.

* Basic

** Packages

*** package archives

set your package archives here, and enable use-package.

I'm in China, so here I use [[https://mirrors.tuna.tsinghua.edu.cn/help/elpa/][tsinghua tuna]].

#+begin_src emacs-lisp
  ;; Initialize package sources
  (require 'package)

  (let (;; tsinghua
        (archives '("http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/"
                    "http://mirrors.tuna.tsinghua.edu.cn/elpa/org/"
                    "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/"))
        ;; ustc
        (archives '("http://mirrors.ustc.edu.cn/elpa/melpa/"
                    "http://mirrors.ustc.edu.cn/elpa/org/"
                    "http://mirrors.ustc.edu.cn/elpa/gnu/"))
        ;; official
        ;; (archives '("https://melpa.org/packages/"
        ;;             "http://orgmode.org/elpa/"
        ;;             "https://elpa.gnu.org/packages/"))
        )
    (setq package-archives `(("melpa" . ,(nth 0 archives))
                             ("org" . ,(nth 1 archives))
                             ("gnu" . ,(nth 2 archives)))))

  (package-initialize)
#+end_src

*** use-package

[[https://jwiegley.github.io/use-package/keywords/][use-package keywords]]

#+begin_src emacs-lisp
  ;; https://www.reddit.com/r/emacs/comments/1rdstn/set_packageenableatstartup_to_nil_for_slightly/
  (setq package-enable-at-startup nil)

  (unless package-archive-contents
    (package-refresh-contents))

    ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

** simpler UI

#+begin_src emacs-lisp
  ;; Produce backtraces when errors occur: can be helpful to diagnose startup issues
  ;; (setq debug-on-error t)
  (add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
  (add-hook 'after-init-hook 'electric-pair-mode)
  (add-hook 'after-init-hook 'electric-indent-mode)
  (add-hook 'after-init-hook 'global-auto-revert-mode)
  (use-package autorevert
    :diminish)
  (setq global-auto-revert-non-file-buffers t
        auto-revert-verbose nil)

  ;; default values
  (setq-default
   help-window-select t
   ;; only enable trailing whitespaces in some modes
   show-trailing-whitespace nil
   buffers-menu-max-size 30
   case-fold-search t
   column-number-mode t
   ediff-split-window-function 'split-window-horizontally
   ediff-window-setup-function 'ediff-setup-windows-plain
   indent-tabs-mode nil
   create-lockfiles nil
   auto-save-default nil
   make-backup-files nil
   mouse-yank-at-point t
   save-interprogram-paste-before-kill t
   scroll-preserve-screen-position 'always
   set-mark-command-repeat-pop t
   tooltip-delay 1.5
   truncate-lines nil
   truncate-partial-width-windows nil)
#+end_src

** Startup Performance

*** garbage collection

Adjust garbage collection threashold for startup and after, garbage collection happens more frequently but in less time

#+begin_src emacs-lisp
  ;; Adjust garbage collection thresholds during startup, and thereafter
  (let ((normal-gc-cons-threshold (* 20 1024 1024))
        (init-gc-cons-threshold (* 128 1024 1024)))
    (setq gc-cons-threshold init-gc-cons-threshold)
    (add-hook 'emacs-startup-hook
              (lambda () (setq gc-cons-threshold (* 20 1024 1024)))))
#+end_src

*** Display startup time

#+begin_src emacs-lisp
  (defun k4i/display-startup-time ()
    (message "init completed in %s with %d garbage collections."
             (format "%.2f seconds"
                     (float-time
                      (time-subtract after-init-time before-init-time)))
             gcs-done))

  (add-hook 'after-init-hook #'k4i/display-startup-time)
#+end_src

** TODO search tools

=("rg" "ag" "pt" "ack" "grep")=

* Keep Folders Clean

We use the [[https://github.com/emacscollective/no-littering/blob/master/no-littering.el][no-littering]] package to keep folders where we edit files and the Emacs configuration folder clean!  It knows about a wide variety of variables for built in Emacs features as well as those from community packages so it can be much easier than finding and setting these variables yourself.

#+begin_src emacs-lisp
  ;; NOTE: If you want to move everything out of the ~/.emacs.d folder
  ;; reliably, set `user-emacs-directory` before loading no-littering!
  ;(setq user-emacs-directory "~/.cache/emacs")

  (use-package no-littering)

  ;; no-littering doesn't set this by default so we must place
  ;; auto save files in the same path as it uses for sessions
  (setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
#+end_src

* Keybinding

** define-key & global-set-key

#+begin_src emacs-lisp
  (global-set-key (kbd "C-x C-b") 'ibuffer)
#+end_src

** evil mode
This configuration uses [[https://evil.readthedocs.io/en/latest/index.html][evil-mode]] for a Vi-like modal editing experience.  [[https://github.com/noctuid/general.el][general.el]] is used for easy keybinding configuration that integrates well with which-key.  [[https://github.com/emacs-evil/evil-collection][evil-collection]] is used to automatically configure various Emacs modes with Vi-like keybindings for evil-mode.

#+begin_src emacs-lisp
  ;; Make ESC quit prompts
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

  (use-package undo-fu)
  (use-package evil
    :init
    ;; set these variables before evil-mode is loaded
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-u-delete t)
    (setq evil-want-C-i-jump nil)
    (setq evil-undo-system 'undo-fu)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))

  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+end_src

** general

*** leader

#+begin_src emacs-lisp
  (use-package general
    :after evil
    :config
    (general-create-definer my-space-leader
      :keymaps '(normal visual)
      :prefix "SPC")

    (my-space-leader
      "d" '(lambda () (interactive) (dired default-directory))
      "f"  '(:ignore t :which-key "file prefix")
      "fd" '(:ignore t :which-key "dotfiles prefix")
      "fde" '((lambda () (interactive) (find-file (expand-file-name "~/.dotfiles/.emacs.d/README.org"))) :which-key "emacs")
      "k" 'kill-this-buffer
      "o"  '(:ignore t :which-key "org prefix")
      "oa" 'org-agenda
      "oc" 'org-capture
      "r" 'resize-window
      "t"  '(:ignore t :which-key "toggles")
      "tt" '(counsel-load-theme :which-key "choose theme")
      "tf" 'treemacs
      "'" 'vterm-toggle-cd
      "=" 'format-all-buffer)

    (general-create-definer my-comma-leader
      :keymaps '(normal visual)
      :prefix ",")

    (my-comma-leader
      "k"  'kill-this-buffer))
#+end_src

*** major leader

use =,= as major mode leader key

** Which Key

[[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.

#+begin_src emacs-lisp
  (use-package which-key
    :init
    (which-key-mode)
    :diminish which-key-mode
    :custom
    (which-key-idle-delay 0.3)
    :diminish which-key-mode)
#+end_src

** Ivy and Counsel

[[https://oremacs.com/swiper/][Ivy]] is an excellent completion framework for Emacs.  It provides a minimal yet powerful selection menu that appears when you open files, switch buffers, and for many other tasks in Emacs.  Counsel is a customized set of commands to replace `find-file` with `counsel-find-file`, etc which provide useful commands for each of the default completion commands.

[[https://github.com/Yevgnen/ivy-rich][ivy-rich]] adds extra columns to a few of the Counsel commands to provide more information about each item.

#+begin_src emacs-lisp
  (use-package ivy
    :after counsel
    :diminish
    :bind (("C-s" . swiper)
           ("C-M-j" . ivy-switch-buffer)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :custom (ivy-use-virtual-buffers t)
    :config
    (ivy-mode 1))

  (use-package ivy-rich
    :after ivy
    :init
    (ivy-rich-mode 1))

  (use-package counsel
    :bind (:map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :custom
    (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
    :config
    (counsel-mode 1))
#+end_src

*** Improved Candidate Sorting with prescient.el

prescient.el provides some helpful behavior for sorting Ivy completion candidates based on how recently or frequently you select them.  This can be especially helpful when using =M-x= to run commands that you don't have bound to a key but still need to access occasionally.

This Prescient configuration is optimized for use in System Crafters videos and streams, check out the [[https://youtu.be/T9kygXveEz0][video on prescient.el]] for more details on how to configure it!

#+begin_src emacs-lisp

  (use-package ivy-prescient
    :after counsel
    :custom
    (ivy-prescient-enable-filtering nil)
    :config
    ;; Uncomment the following line to have sorting remembered across sessions!
    ;(prescient-persist-mode 1)
    (ivy-prescient-mode 1))

#+end_src

** Helpful Help Commands

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp
  (use-package helpful
    :commands (helpful-callable helpful-variable helpful-command helpful-key)
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))
#+end_src

** window

this is from [[https://www.emacswiki.org/emacs/WindowResize][emacswiki: WindowResize]]

#+begin_src emacs-lisp
  (defvar enlarge-window-height-char ?k)
  (defvar shrink-window-height-char ?j)
  (defvar enlarge-window-width-char ?l)
  (defvar shrink-window-width-char ?h)
  (defun resize-window (&optional arg)
     "Interactively resize the selected window.
  Repeatedly prompt whether to enlarge or shrink the window until the
  response is neither `enlarge-window-char' or `shrink-window-char'.
  When called with a prefix arg, resize the window by ARG lines."
     (interactive "p")
     ;; by default arg is 1, too slow to resize
     (setq arg 3)
     (let ((prompt (format "Enlarge/Shrink window (%c/%c/%c/%c)? "
                           enlarge-window-height-char shrink-window-height-char
                           enlarge-window-width-char shrink-window-width-char))
          response)
       (while (progn
               (setq response (read-event prompt))
               (cond ((equal response enlarge-window-height-char)
                      (enlarge-window arg)
                      t)
                     ((equal response shrink-window-height-char)
                      (enlarge-window (- arg))
                      t)
                     ((equal response enlarge-window-width-char)
                      (enlarge-window-horizontally arg)
                      t)
                     ((equal response shrink-window-width-char)
                      (enlarge-window-horizontally (- arg))
                      t)
                     (t nil))))
       (push response unread-command-events)))
#+end_src

* UI

** Basic

#+BEGIN_SRC emacs-lisp
  ;; adjust font size for your system
  (defvar k4i/default-font-size 200)
  (defvar k4i/default-variable-font-size 200)

  ;; Make frame transparency overridable
  ;; (defvar k4i/frame-transparency '(100 . 90))

  (setq inhibit-startup-message t)

  (scroll-bar-mode -1) ; Disable visible scrollbar
  (tool-bar-mode -1) ; Disable the toolbar
  (tooltip-mode -1) ; Disable tooltips
  (set-fringe-mode 10) ; Give some breathing room

  (menu-bar-mode -1) ; Disable the menu bar

  ;; Set up the visible bell
  (setq visible-bell t)

  ;; Set frame transparency
  ;; (set-frame-parameter (selected-frame) 'alpha k4i/frame-transparency)
  ;; (add-to-list 'default-frame-alist `(alpha . ,k4i/frame-transparency))
  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  (add-to-list 'default-frame-alist '(fullscreen . maximized))

  (global-display-line-numbers-mode t)
  (column-number-mode) ; show column number
  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  eshell-mode-hook
                  treemacs-mode-hook))
      (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+END_SRC

** Cursor

#+begin_src emacs-lisp
  (use-package beacon
    :custom
    (beacon-lighter "")
    (beacon-size 20)
    :config
    (beacon-mode 1))
#+end_src

** whitespaces

remove trailing whitespaces

#+begin_src emacs-lisp
  (defun k4i/show-trailing-whitespace ()
    "Enable display of trailing whitespace in this buffer."
    (setq-local show-trailing-whitespace t))

  (dolist (hook '(prog-mode-hook text-mode-hook conf-mode-hook))
    (add-hook hook 'k4i/show-trailing-whitespace))

  (add-hook 'before-save-hook
            'delete-trailing-whitespace)

  ;; M-SPC
  (global-set-key [remap just-one-space] 'cycle-spacing)
#+end_src

set whitespace display style (with =whitespace= package)

#+begin_src emacs-lisp
#+end_src

** Font

*** text

   #+BEGIN_SRC emacs-lisp
     (set-face-attribute 'default nil :font "DejaVu Sans Mono" :height k4i/default-font-size)

     ;; set the fixed pitch face
     (set-face-attribute 'fixed-pitch nil :font "DejaVu Sans Mono" :height 0.9)

     ;; Set the variable pitch face
     (set-face-attribute 'variable-pitch nil :font "Cantarell" :height 1.0 :weight 'regular)
   #+END_SRC

*** icons

#+begin_src emacs-lisp
  (use-package all-the-icons)
#+end_src

*** emojis

** Colored Parens

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] is useful in programming modes because it colorizes nested parentheses and brackets according to their nesting depth.  This makes it a lot easier to visually match parentheses in Emacs Lisp code without having to count them yourself.

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook
    (prog-mode . rainbow-delimiters-mode))
#+end_src

show-paren-mode

#+begin_src emacs-lisp
  (add-hook 'after-init-hook 'show-paren-mode)
#+end_src

** Command Log Mode

[[https://github.com/lewang/command-log-mode][command-log-mode]] is useful for displaying a panel showing each key binding you use in a panel on the right side of the frame.  Great for live streams and screencasts!

#+begin_src emacs-lisp
  (use-package command-log-mode
    :commands command-log-mode)
#+end_src

** Color Theme

run =M-x counsel-load-theme= to choose between them easily.

#+begin_src emacs-lisp
(use-package doom-themes
  :init (load-theme 'doom-gruvbox-light t))
#+end_src

** Better Modeline

check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run =M-x all-the-icons-install-fonts= so that mode line icons display correctly.

#+begin_src emacs-lisp
  (use-package doom-modeline
    :custom
    (doom-modeline-height 15)
    :hook
    (after-init . doom-modeline-mode))
#+end_src

* Snippets/yasnippet

#+begin_src emacs-lisp
  (use-package yasnippet
    :hook ((prog-mode conf-mode text-mode snippet-mode) . yas-minor-mode))

  (use-package yasnippet-snippets
    :after (yasnippet))

  ;; (advice-add 'company-complete-common :before (lambda ()
  ;;                                 (setq my-company-point (point))))
  ;; (advice-add 'company-complete-common :after (lambda ()
  ;;                                 (when (equal my-company-point (point)) (yas-expand))))
#+end_src

* Org Mode

** Basic Config

*** Better Font Faces

The =k4i/org-font-setup= function configures various text faces to tweak the sizes of headings and use variable width fonts in most cases so that it looks more like we're editing a document in =org-mode=.  We switch back to fixed width (monospace) fonts for code blocks and tables so that they display correctly.

#+begin_src emacs-lisp
  (defun k4i/org-font-setup ()
    ;; Set faces for heading levels
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      (set-face-attribute (car face) nil :font "Cantarell" :weight 'bold :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil    :foreground nil :inherit 'fixed-pitch)
    ;; (set-face-attribute 'org-table nil    :inherit 'fixed-pitch)
    (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil     :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil    :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil  :inherit 'fixed-pitch)
    (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
    (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch))
#+end_src

*** Org Mode

#+begin_src emacs-lisp
  (defun k4i/org-mode-setup ()
    (org-indent-mode)
    (variable-pitch-mode 1)
    (visual-line-mode 1))

  (use-package org
    :pin org
    :commands (org-capture org-agenda)
    :hook (org-mode . k4i/org-mode-setup)
    :custom
    (org-image-actual-width (/ (nth 3 (assq 'geometry (frame-monitor-attributes))) 3))
    (org-startup-folded t)
    (org-directory (expand-file-name "Org" (getenv "HOME")))
    (org-ellipsis " ▾")
    (org-agenda-start-with-log-mode t)
    ;; (org-hide-emphasis-markers t)
    (org-log-done 'time)
    (org-log-into-drawer t)
    ;; org-directory/GTD
    (org-agenda-files (list (expand-file-name "GTD" org-directory)))
    ;; tags: C-c C-q
    (org-tag-alist
     '((:startgroup)
       ("@notes" . ?n)
       ("@workspace_setup" . ?w)
       ("@Data_Structure_and_Algorithm" . ?d)
       (:endgroup)
       ("idea" . ?i)))
    :config
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

    ;; C-c C-t
    (setq org-todo-keywords
          '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
            (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

    (setq org-refile-targets
          '(("Archive.org" :maxlevel . 1)
            ("Tasks.org" :maxlevel . 1)))

    ;; Save Org buffers after refiling!
    (advice-add 'org-refile :after 'org-save-all-org-buffers)

    (k4i/org-font-setup))
#+end_src

*** Nicer Heading Bullets

[[https://github.com/sabof/org-bullets][org-bullets]] replaces the heading stars in =org-mode= buffers with nicer looking characters that you can control.  Another option for this is [[https://github.com/integral-dw/org-superstar-mode][org-superstar-mode]] which we may cover in a later video.

#+begin_src emacs-lisp
  (use-package org-bullets
    :hook (org-mode . org-bullets-mode)
    :custom
    (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))
#+end_src

*** center org buffer

#+begin_src emacs-lisp
  (defun k4i/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . k4i/org-mode-visual-fill)
    :config
    (advice-add 'text-scale-adjust :after #'visual-fill-column-adjust))
#+end_src

*** key bindings

#+begin_src emacs-lisp
  (general-evil-define-key '(normal visual insert) org-mode-map
    "M-h" 'org-metaleft
    "M-H" 'org-shiftmetaleft
    "M-l" 'org-metaright
    "M-L" 'org-shiftmetaright
    "M-j" 'org-metadown
    "M-J" 'org-shiftmetadown
    "M-k" 'org-metaup
    "M-K" 'org-shiftmetaup)
#+end_src

** Org Agenda

*** custom commands

#+begin_src emacs-lisp
  ;; Configure custom agenda views
  (with-eval-after-load 'org-agenda
    (setq org-agenda-custom-commands
          '(("d" "Dashboard"
             ((agenda "" ((org-deadline-warning-days 14)))
              (todo "NEXT"
                    ((org-agenda-overriding-header "Next Tasks")))
              (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

            ("n" "Next Tasks"
             ((todo "NEXT"
                    ((org-agenda-overriding-header "Next Tasks")))))

            ("w" "Workflow Status"
             ((todo "WAIT"
                    ((org-agenda-overriding-header "Waiting on External")
                     (org-agenda-files org-agenda-files)))
              (todo "REVIEW"
                    ((org-agenda-overriding-header "In Review")
                     (org-agenda-files org-agenda-files)))
              (todo "PLAN"
                    ((org-agenda-overriding-header "In Planning")
                     (org-agenda-todo-list-sublevels nil)
                     (org-agenda-files org-agenda-files)))
              (todo "BACKLOG"
                    ((org-agenda-overriding-header "Project Backlog")
                     (org-agenda-todo-list-sublevels nil)
                     (org-agenda-files org-agenda-files)))
              (todo "READY"
                    ((org-agenda-overriding-header "Ready for Work")
                     (org-agenda-files org-agenda-files)))
              (todo "ACTIVE"
                    ((org-agenda-overriding-header "Active Projects")
                     (org-agenda-files org-agenda-files)))
              (todo "COMPLETED"
                    ((org-agenda-overriding-header "Completed Projects")
                     (org-agenda-files org-agenda-files)))
              (todo "CANC"
                    ((org-agenda-overriding-header "Cancelled Projects")
                     (org-agenda-files org-agenda-files))))))))
#+end_src

*** Org Habit

#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (require 'org-habit)
    (add-to-list 'org-modules 'org-habit)
    (setq org-habit-graph-column 60))
#+end_src

** Drag and Drop using org-download

#+begin_src emacs-lisp
  (use-package org-download
    :after org
    :hook ((org-mode dired-mode) . org-download-enable)
    :custom
    (org-download-image-dir "images")
    (org-dwnload-method 'directory)
    (org-download-heading-lvl nil)
    (org-download-timestamp "%Y%m%d-%H%M%S_")
    ;; (org-download-annotate-function (lambda (_link) ""))
    :bind
    ("C-M-y" .
     (lambda (&optional noask)
       (interactive "P")
       (let ((file
              (if (not noask)
                  (read-string (format "Filename [%s]: " org-download-screenshot-basename)
                               nil nil org-download-screenshot-basename)
                nil)))
         (org-download-clipboard file))))
    :config
    (require 'org-download))
#+end_src

** Org Export

*** revealjs

#+begin_src emacs-lisp
  (use-package ox-reveal
    :after ox
    :custom
    ;; or use a online revealjs
    ;; #+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
    (org-reveal-root (concat "file://" (expand-file-name "~/app/revealjs/reveal.js-master/"))))
#+end_src

*** markdown/hugo

#+begin_src emacs-lisp
  (use-package ox-hugo
    :after ox)
#+end_src

*** latex/pdf

need to install some dependencies:

#+begin_src shell
  pip install pygments
#+end_src

#+begin_src emacs-lisp
  (with-eval-after-load 'ox-latex
    ;; http://orgmode.org/worg/org-faq.html#using-xelatex-for-pdf-export
    ;; latexmk runs pdflatex/xelatex (whatever is specified) multiple times
    ;; automatically to resolve the cross-references.
    (setq org-latex-pdf-process '("latexmk -xelatex -quiet -shell-escape -f %f"))
    ;; (setq org-latex-pdf-process '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
    (add-to-list 'org-latex-classes
                 '("elegantpaper"
                   "\\documentclass[lang=cn]{elegantpaper}
                 [NO-DEFAULT-PACKAGES]
                 [PACKAGES]
                 [EXTRA]"
                   ("\\section{%s}" . "\\section*{%s}")
                   ("\\subsection{%s}" . "\\subsection*{%s}")
                   ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                   ("\\paragraph{%s}" . "\\paragraph*{%s}")
                   ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
    (add-to-list 'org-latex-classes
                 '("beamer"
                   "\\documentclass[presentation]{beamer}"
                   ("\\section{%s}" . "\\section*{%s}")
                   ("\\subsection{%s}" . "\\subsection*{%s}")
                   ("\\subsubsection{%s}" . "\\subsubsection*{%s}")))
    (setq org-latex-listings 'minted)
    (setq org-latex-minted-options
          '(("frame" "none")
            ("linenos" "false")
            ("breaklines" "true")
            ("bgcolor" "lightgray")))
    (add-to-list 'org-latex-packages-alist '("" "minted")))
#+end_src

** Org Babel

*** Configure Babel Languages

To execute or export code in =org-mode= code blocks, you'll need to set up =org-babel-load-languages= for each language you'd like to use.  [[https://orgmode.org/worg/org-contrib/babel/languages/index.html][This page]] documents all of the languages that you can use with =org-babel=.

#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (org-babel-do-load-languages
        'org-babel-load-languages
        '((emacs-lisp . t)
        (python . t)))

    (push '("conf-unix" . conf-unix) org-src-lang-modes))
#+end_src

*** Tangle Config Files

This snippet adds a hook to =org-mode= buffers so that =k4i/org-babel-tangle-config= gets executed each time such a buffer gets saved.  This function checks to see if the file being saved is inside =user-emacs-directory=, and if so, automatically exports the configuration here to the associated output files.

The line =#+PROPERTY: header-args:emacs-lisp :tangle ./init.el= at the beginning of this document tells that emacs-lisp blocks will be tangled to =./init.el=.

#+begin_src emacs-lisp
  ;; Automatically tangle our org config file in the emacs directory when we save it
  (defun k4i/org-babel-tangle-config ()
    "tangle any org-mode file inside user-emacs-directory"
    (when (string-equal (file-name-directory (buffer-file-name))

                        (let (
                              ;; (emacs-config-dir user-emacs-directory)
                              (emacs-config-dir "~/.dotfiles/.emacs.d/")
                              )
                          (expand-file-name emacs-config-dir))
                        )
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'k4i/org-babel-tangle-config)))
#+end_src

** Capture Templates

*** task

#+begin_src emacs-lisp
  (with-eval-after-load 'org-capture
    (add-to-list 'org-capture-templates
                 '("t" "Task"  entry
                   (file "GTD/Tasks.org")
                   "* TODO %?\nDEADLINE: %(format-time-string \"%<<%Y-%m-%d %a>>\")\n"
                   :unnarrowed t)))
#+end_src

*** Contact

#+begin_src emacs-lisp
  (with-eval-after-load 'org-capture
    (add-to-list 'org-capture-templates
                 '("c" "Contact"  entry
                   (file "GTD/Contacts.org")
                   "* %?\n:PROPERTIES:\n:ADDRESS:\n:PHONE:\n:BDAY: %(format-time-string \"%<<%Y-%m-%d %a +1y>>\")\n:EMAIL:\n:END:\n"
                   :unnarrowed t)))
#+end_src

*** habit

#+begin_src emacs-lisp
  (with-eval-after-load 'org-capture
    (add-to-list 'org-capture-templates
                 '("h" "Habit"  entry
                   (file "GTD/Habits.org")
                   "* NEXT %?\nSCHEDULED: %(format-time-string \"%<<%Y-%m-%d %a .+1d/3d>>\")\n:PROPERTIES:\n:STYLE: habit\n:REPEAT_TO_STATE: NEXT\n:END:\n"
                   :unnarrowed t)))
#+end_src

*** hugo post

#+begin_src emacs-lisp
  (defun org-hugo-new-subtree-post-capture-template ()
    "Returns `org-capture' template string for new Hugo post.
   See `org-capture-templates' for more information."
    (let* (;; http://www.holgerschurig.de/en/emacs-blog-from-org-to-hugo/
           (date (format-time-string (org-time-stamp-format :long :inactive) (org-current-time)))
           (title (read-from-minibuffer "Post Title: ")) ;Prompt to enter the post title
           (fname (org-hugo-slug title)))
      (mapconcat #'identity
                 `(
                   ,(concat "\n* TODO " title "  :@cat:tag:")
                   ":PROPERTIES:"
                   ,(concat ":EXPORT_HUGO_BUNDLE: " fname)
                   ":EXPORT_FILE_NAME: index"
                   ,(concat ":EXPORT_DATE: " date) ;Enter current date and time
                   ":EXPORT_HUGO_CUSTOM_FRONT_MATTER: :image \"/images/icons/tortoise.png\""
                   ":EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :libraries '(mathjax)"
                   ":EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description \"this is a description\""
                   ":END:"
                   "%?\n")
                 "\n")))
#+end_src

#+begin_src emacs-lisp
  (with-eval-after-load 'org-capture
    (setq hugo-content-org-dir "~/git-repo/blog/blog-src/content-org")
    (add-to-list 'org-capture-templates
                 `("pe"                ;`org-capture' binding + h
                   "Hugo Post (en)"
                   entry
                   ;; It is assumed that below file is present in `org-directory'
                   ;; and that it has a "Blog Ideas" heading. It can even be a
                   ;; symlink pointing to the actual location of all-posts.org!
                   (file ,(expand-file-name "all-posts.en.org" hugo-content-org-dir))
                   (function org-hugo-new-subtree-post-capture-template)))
    (add-to-list 'org-capture-templates
                 `("pz"
                   "Hugo Post (zh)"
                   entry
                   (file ,(expand-file-name "all-posts.zh.org" hugo-content-org-dir))
                   (function org-hugo-new-subtree-post-capture-template)))
    (add-to-list 'org-capture-templates '("p" "Hugo Post")))
#+end_src

** Org Roam

*** basic

#+begin_src emacs-lisp
  (use-package org-roam
    :after org
    :init
    (setq org-roam-v2-ack t)
    :custom
    (org-roam-directory (expand-file-name "Org-Roam" org-directory))
    (org-roam-complete-everywhere t)
    :config
    (org-roam-setup)
    :bind
    (("C-c n f" . org-roam-node-find)
     ("C-c n r" . org-roam-node-random)
     :map org-mode-map
     ("C-c n i" . org-roam-node-insert)
     ("C-c n o" . org-id-get-create)
     ("C-c n t" . org-roam-tag-add)
     ("C-c n a" . org-roam-alias-add)
     ("C-c n l" . org-roam-buffer-toggle)
     ("C-M-i" . completion-at-point)))
#+end_src

*** ui

#+begin_src emacs-lisp
  (use-package org-roam-ui
    :after org-roam
    :custom
    (org-roam-ui-sync-theme t)
    (org-roam-ui-follow t)
    (org-roam-ui-update-on-save t))
#+end_src

* Development

** camelcase motion

#+begin_src emacs-lisp
  (use-package subword
    :hook (prog-mode . subword-mode)
    :diminish)
#+end_src

** symbol overlay

#+begin_src emacs-lisp
  (use-package symbol-overlay
    :hook ((prog-mode html-mode yaml-mode conf-mode) . symbol-overlay-mode)
    :bind (:map symbol-overlay-mode-map
                ("M-i" . symbol-overlay-put)
                ("M-I" . symbol-overlay-remove-all)
                ("M-n" . symbol-overlay-jump-next)
                ("M-p" . symbol-overlay-jump-prev))
   :diminish)
#+end_src

** flycheck

#+begin_src emacs-lisp
      (use-package flycheck
        :init (global-flycheck-mode)
        :custom
        (flycheck-display-errors-function #'flycheck-display-error-messages-unless-error-list))
#+end_src

** Company Mode

[[http://company-mode.github.io/][Company Mode]] provides a nicer in-buffer completion interface than =completion-at-point= which is more reminiscent of what you would expect from an IDE.  We add a simple configuration to make the keybindings a little more useful (=TAB= now completes the selection and initiates completion at the current location if needed).

We also use [[https://github.com/sebastiencs/company-box][company-box]] to further enhance the look of the completions with icons and better overall presentation.

#+begin_src emacs-lisp
  (use-package company
    :init (global-company-mode)
    :bind (:map company-mode-map
                ("M-/" . company-complete)
                ;; not smart enough
                ;; ("<tab>" . company-indent-or-complete-common)
                :map company-active-map
                ("RET" . nil)
                ("<return>" . nil)
                ("<tab>" . company-complete-selection)
                ("M-/" . company-other-backend))
    :custom
    (company-global-modes '(not message-mode help-mode magit-mode))
    (company-minimum-prefix-length 1)
    (company-idle-delay 0.0)
    (company-tooltip-aligh-annotations t)
    ;; easy navigation to candidates with M-<n>
    (company-show-numbers t)
    (company-dabbrev-downcase nil)
    (company-backends '((company-files
                         company-yasnippet
                         company-keywords
                         company-capf)
                        (company-abbrev company-dabbrev)))
    :config
    (defun my-company-yasnippet-disable-inline (fun command &optional arg &rest _ignore)
      "Enable yasnippet but disable it inline."
      (if (eq command 'prefix)
          (when-let ((prefix (funcall fun 'prefix)))
            (unless (memq (char-before (- (point) (length prefix))) '(?. ?> ?\())
              prefix))
        (funcall fun command arg)))
    (advice-add #'company-yasnippet :around #'my-company-yasnippet-disable-inline)
    :diminish company-mode)

  (use-package company-box
    :hook (company-mode . company-box-mode))
#+end_src

** Commenting

Emacs' built in commenting functionality =comment-dwim= (usually bound to =M-;=) doesn't always comment things in the way you might expect so we use [[https://github.com/redguardtoo/evil-nerd-commenter][evil-nerd-commenter]] to provide a more familiar behavior.  I've bound it to =M-/= since other editors sometimes use this binding but you could also replace Emacs' =M-;= binding with this command.

#+begin_src emacs-lisp
  (use-package evil-nerd-commenter
    :bind ("C-/" . evilnc-comment-or-uncomment-lines))
#+end_src

** Formatting

#+begin_src emacs-lisp
  (use-package format-all
    :hook
    (prog-mode . format-all-mode)
    (format-all-mode . format-all-ensure-formatter))
#+end_src

** Projectile

[[https://projectile.mx/][Projectile]] is a project management library for Emacs which makes it a lot easier to navigate around code projects for various languages.  Many packages integrate with Projectile so it's a good idea to have it installed even if you don't use its commands directly.

#+begin_src emacs-lisp
  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :custom ((projectile-completion-system 'ivy))
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :init
    ;; NOTE: Set this to the folder where you keep your Git repos!
    (when (file-directory-p "~/git-repo/")
      (setq projectile-project-search-path '("~/git-repo/")))
    (setq projectile-switch-project-action #'projectile-dired))

  (use-package counsel-projectile
    :after projectile
    :config (counsel-projectile-mode))
#+end_src

* Git

** Magit

[[https://magit.vc/][Magit]] is the best Git interface I've ever used.  Common Git operations are easy to execute quickly using Magit's command panel system.

#+begin_src emacs-lisp
  (use-package magit
    :commands magit-status
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  ;; NOTE: Make sure to configure a GitHub token before using this package!
  ;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
  ;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
  (use-package forge
    :after magit)
#+end_src

* lsp-mode

** lsp-mode

We use the excellent [[https://emacs-lsp.github.io/lsp-mode/][lsp-mode]] to enable IDE-like functionality for many different programming languages via "language servers" that speak the [[https://microsoft.github.io/language-server-protocol/][Language Server Protocol]].  Before trying to set up =lsp-mode= for a particular language, check out the [[https://emacs-lsp.github.io/lsp-mode/page/languages/][documentation for your language]] so that you can learn which language servers are available and how to install them.

The =lsp-keymap-prefix= setting enables you to define a prefix for where =lsp-mode='s default keybindings will be added.  I *highly recommend* using the prefix to find out what you can do with =lsp-mode= in a buffer.

The =which-key= integration adds helpful descriptions of the various keys so you should be able to learn a lot just by pressing =C-c l= in a =lsp-mode= buffer and trying different things that you find there.

#+begin_src emacs-lisp
  (defun k4i/lsp-mode-setup ()
    (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
    (lsp-headerline-breadcrumb-mode))

  (use-package lsp-mode
    :commands (lsp lsp-deferred)
    :hook (lsp-mode . k4i/lsp-mode-setup)
    :init
    (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
    :config
    (lsp-enable-which-key-integration t))
#+end_src

** lsp-ui

[[https://emacs-lsp.github.io/lsp-ui/][lsp-ui]] is a set of UI enhancements built on top of =lsp-mode= which make Emacs feel even more like an IDE.  Check out the screenshots on the =lsp-ui= homepage (linked at the beginning of this paragraph) to see examples of what it can do.

#+begin_src emacs-lisp

  (use-package lsp-ui
    :hook (lsp-mode . lsp-ui-mode)
    :custom
    (lsp-ui-doc-position 'bottom))

#+end_src

** lsp-ivy

[[https://github.com/emacs-lsp/lsp-ivy][lsp-ivy]] integrates Ivy with =lsp-mode= to make it easy to search for things by name in your code.  When you run these commands, a prompt will appear in the minibuffer allowing you to type part of the name of a symbol in your code.  Results will be populated in the minibuffer so that you can find what you're looking for and jump to that location in the code upon selecting the result.

Try these commands with =M-x=:

- =lsp-ivy-workspace-symbol= - Search for a symbol name in the current project workspace
- =lsp-ivy-global-workspace-symbol= - Search for a symbol name in all active project workspaces

#+begin_src emacs-lisp
  (use-package lsp-ivy
    :after lsp)
#+end_src

* dap-mode

[[https://emacs-lsp.github.io/dap-mode/][dap-mode]] is an excellent package for bringing rich debugging capabilities to Emacs via the [[https://microsoft.github.io/debug-adapter-protocol/][Debug Adapter Protocol]].  You should check out the [[https://emacs-lsp.github.io/dap-mode/page/configuration/][configuration docs]] to learn how to configure the debugger for your language.  Also make sure to check out the documentation for the debug adapter to see what configuration parameters are available to use for your debug templates!

#+begin_src emacs-lisp
  (use-package dap-mode
    :after lsp-mode
    ;; Uncomment the config below if you want all UI panes to be hidden by default!
    ;; :custom
    ;; (lsp-enable-dap-auto-configure nil)
    ;; :config
    ;; (dap-ui-mode 1)
    :commands dap-debug
    :config
    ;; Set up Node debugging
    (require 'dap-node)
    (dap-node-setup) ;; Automatically installs Node debug adapter if needed

    (require 'dap-python)

    ;; C/C++
    ;; lldb is a debugger that supports: C, C++, Objective-C, Swift
    (require 'dap-lldb)
    ;; set the debugger executable (c++), by default it looks for it under .emacs.d/..
    (setq dap-lldb-debug-program '("lldb-vscode"))

    ;; Bind `C-c l d` to `dap-hydra` for easy access
    (general-define-key
      :keymaps 'lsp-mode-map
      :prefix lsp-keymap-prefix
      "d" '(dap-hydra t :wk "debugger")))
#+end_src

* Languages
** TypeScript

This is a basic configuration for the TypeScript language so that =.ts= files activate =typescript-mode= when opened.  We're also adding a hook to =typescript-mode-hook= to call =lsp-deferred= so that we activate =lsp-mode= to get LSP features every time we edit TypeScript code.

#+begin_src emacs-lisp
  (use-package typescript-mode
    :mode "\\.ts\\'"
    :hook (typescript-mode . lsp-deferred)
    :config
    (setq typescript-indent-level 2))
#+end_src

*Important note!*  For =lsp-mode= to work with TypeScript (and JavaScript) you will need to install a language server on your machine.  If you have Node.js installed, the easiest way to do that is by running the following command:

#+begin_src shell :tangle no
npm install -g typescript-language-server typescript
#+end_src

This will install the [[https://github.com/theia-ide/typescript-language-server][typescript-language-server]] and the TypeScript compiler package.

** Python

We use =lsp-mode= and =dap-mode= to provide a more complete development environment for Python in Emacs.  Check out [[https://emacs-lsp.github.io/lsp-mode/page/lsp-pyls/][the =pyls= configuration]] in the =lsp-mode= documentation for more details.

Make sure you have the =pyls= language server installed before trying =lsp-mode=!

#+begin_src sh :tangle no
pip install --user "python-lsp-server"
#+end_src

There are a number of other language servers for Python so if you find that =pyls= doesn't work for you, consult the =lsp-mode= [[https://emacs-lsp.github.io/lsp-mode/page/languages/][language configuration documentation]] to try the others!

#+begin_src emacs-lisp
  (use-package python-mode
    :ensure t
    :hook (python-mode . lsp-deferred)
    :custom
    ;; NOTE: Set these if Python 3 is called "python3" on your system!
    ;; (python-shell-interpreter "python3")
    ;; (dap-python-executable "python3")
    (dap-python-debugger 'debugpy)
    :config
    (require 'dap-python))
#+end_src

You can use the pyvenv package to use =virtualenv= environments in Emacs.  The =pyvenv-activate= command should configure Emacs to cause =lsp-mode= and =dap-mode= to use the virtual environment when they are loaded, just select the path to your virtual environment before loading your project.

#+begin_src emacs-lisp
  (use-package pyvenv
    :after python-mode
    :config
    (pyvenv-mode 1))
#+end_src

** C/C++

* Terminal - vterm

** vterm

[[https://github.com/akermu/emacs-libvterm/][vterm]] is an improved terminal emulator package which uses a compiled native module to interact with the underlying terminal applications.  This enables it to be much faster than =term-mode= and to also provide a more complete terminal emulation experience.

Make sure that you have the [[https://github.com/akermu/emacs-libvterm/#requirements][necessary dependencies]] installed before trying to use =vterm= because there is a module that will need to be compiled before you can use it successfully.

#+begin_src emacs-lisp
  (use-package vterm
    :commands vterm
    :config
    (setq term-prompt-regexp "^[^#$%>❯\n]*[#$%>❯] *")  ;; Set this to match your custom shell prompt
    ;;(setq vterm-shell "zsh")                       ;; Set this to customize the shell to launch
    (setq vterm-max-scrollback 10000))
#+end_src

** vterm-toggle

#+begin_src emacs-lisp
  (use-package vterm-toggle
    :custom
    (vterm-toggle-hide-method 'delete-window)
    :hook
    (vterm-toggle-show . evil-insert-state)
    :config
    (setq vterm-toggle-fullscreen-p nil)
    (add-to-list 'display-buffer-alist
                 '((lambda (bufname _)
                     (with-current-buffer bufname (equal major-mode 'vterm-mode)))
                  (display-buffer-reuse-window display-buffer-in-direction)
                  ;;display-buffer-in-direction/direction/dedicated is added in emacs27
                  (direction . bottom)
                  (dedicated . t) ;dedicated is supported in emacs27
                  (reusable-frames . visible)
                  (window-height . 0.3))))
#+end_src

* File Management

** Dired

Dired is a built-in file manager for Emacs.

*** Key Bindings

**** Navigation

*Evil* (function)
- =j= - next line
- =k= - previous line
- =h= (dired-single-up-directory) - go to parent directory
- =^= (dired-up-directory) - go to parent directory (but *new buffer*)
- =l= (dired-single-buffer) - Open file in current buffer (if not directory, then use new buffer created)
- =RET= (dired-find-file) - Open file in "current" window (but *new buffer*)
- =g o= (dired-view-file) - Open file but in a "preview" mode, close with =q=
- =g O= - Open file in "other" window
- =M-RET= - Open file in "other" window without focusing (previewing files)
- =J= (dired-goto-file) - jump to file in buffer, or just use =C-s=
- =g r= (revert-buffer) - Refresh the buffer with =revert-buffer= after changing configuration (and after filesystem changes!)

**** Marking files

- =m= - Marks a file
- =u= - Unmarks a file
- =U= - Unmarks all files in buffer
- =* t= / =t= - Inverts marked files in buffer
- =% m= - Mark files in buffer using regular expression
- =*= - Lots of other auto-marking functions
- =k= / =K= - "Kill" marked items (refresh buffer with =g= / =g r= to get them back)
- Many operations can be done on a single file if there are no active marks!

**** Copying and Renaming files

- =C= - Copy marked files (or if no files are marked, the current file)
- Copying single and multiple files
- =U= - Unmark all files in buffer
- =R= - Rename marked files, renaming multiple is a move!
- =% R= - Rename based on regular expression: =^test= , =old-\&=

*Power command*: =C-x C-q= (=dired-toggle-read-only=) - Makes all file names in the buffer editable directly to rename them!  Press =Z Z= to confirm renaming or =Z Q= to abort.

**** Deleting files

- =D= - Delete current file
- =d= - Mark file for deletion
- =x= - Execute deletion for marks
- =delete-by-moving-to-trash= - Move to trash instead of deleting permanently

**** Creating and extracting archives

- =Z= - Compress or uncompress a file or folder to (=.tar.gz=)
- =c= - Compress selection to a specific file
- =dired-compress-files-alist= - Bind compression commands to file extension

**** Other common operations

- =T= - Touch (change timestamp)
- =M= - Change file mode
- =O= - Change file owner
- =G= - Change file group
- =S= - Create a symbolic link to this file
- =L= - Load an Emacs Lisp file into Emacs

*** Configuration

#+begin_src emacs-lisp
  (use-package dired
    :ensure nil
    :commands (dired dired-jump)
    :bind (("C-x C-j" . dired-jump))
    :custom ((dired-listing-switches "-agho --group-directories-first"))
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "h" 'dired-single-up-directory
      "l" 'dired-single-buffer))

  ;; use single buffer
  (use-package dired-single
    :commands (dired dired-jump))

  ;; use all-the-icons icon in dired
  (use-package all-the-icons-dired
    :hook (dired-mode . all-the-icons-dired-mode))

  (use-package dired-subtree
    :after dired
    :bind (:map dired-mode-map
                ("<tab>" . dired-subtree-toggle)
                ("<C-tab>" . dired-subtree-cycle)
                ("<S-iso-lefttab>" . dired-subtree-remove)))

  (use-package dired-open
    :commands (dired dired-jump)
    :general
    ("C-c o" 'dired-open-xdg)
    :config
    ;; by default <Enter> does not use dired-open-xdg
    ;; (add-to-list 'dired-open-functions #'dired-open-xdg t)
    (setq dired-open-extensions '(("png" . "feh")
                                  ("mkv" . "mpv"))))

  (use-package dired-hide-dotfiles
    ;; :hook (dired-mode . dired-hide-dotfiles-mode)
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "H" 'dired-hide-dotfiles-mode))
#+end_src

** Treemacs

*** lsp-treemacs

[[https://github.com/emacs-lsp/lsp-treemacs][lsp-treemacs]] provides nice tree views for different aspects of your code like symbols in a file, references of a symbol, or diagnostic messages (errors and warnings) that are found in your code.

Try these commands with =M-x=:

- =lsp-treemacs-symbols= - Show a tree view of the symbols in the current file
- =lsp-treemacs-references= - Show a tree view for the references of the symbol under the cursor
- =lsp-treemacs-error-list= - Show a tree view for the diagnostic messages in the project

This package is built on the [[https://github.com/Alexander-Miller/treemacs][treemacs]] package which might be of some interest to you if you like to have a file browser at the left side of your screen in your editor.

#+begin_src emacs-lisp
  (use-package lsp-treemacs
    :after lsp)
#+end_src

*** treemacs

#+begin_src emacs-lisp
  (use-package treemacs
    :custom
    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-project-follow-mode t)
    (treemacs-fringe-indicator-mode t))
#+end_src

*** treemacs-evil

#+begin_src emacs-lisp
  (use-package treemacs-evil
    :after treemacs evil)
#+end_src

* Proxy

** Socks Proxy

#+begin_src emacs-lisp
  (defun proxy-socks-show ()
    "Show SOCKS proxy."
    (interactive)
    (when (fboundp 'cadddr)
      (if (bound-and-true-p socks-noproxy)
          (message "Current SOCKS%d proxy is %s:%d"
                   (cadddr socks-server) (cadr socks-server) (caddr socks-server))
        (message "No SOCKS proxy"))))

  (defun proxy-socks-enable ()
    "Enable SOCKS proxy."
    (interactive)
    (require 'socks)
    (setq url-gateway-method 'socks
          socks-noproxy '("localhost")
          socks-server '("Default server" "127.0.0.1" 1081 5))
    (setenv "all_proxy" "socks5://127.0.0.1:1081")
    (proxy-socks-show))

  (defun proxy-socks-disable ()
    "Disable SOCKS proxy."
    (interactive)
    (require 'socks)
    (setq url-gateway-method 'native
          socks-noproxy nil)
    (setenv "all_proxy" "")
    (proxy-socks-show))

  (defun proxy-socks-toggle ()
    "Toggle SOCKS proxy."
    (interactive)
    (require 'socks)
    (if (bound-and-true-p socks-noproxy)
        (proxy-socks-disable)
      (proxy-socks-enable)))
#+end_src

** Http Proxy

#+begin_src  emacs-lisp
  ;; Configure network proxy
  (setq my-http-proxy "127.0.0.1:1080")
  (defun proxy-http-show ()
    "Show http/https proxy."
    (interactive)
    (if url-proxy-services
        (message "Current proxy is \"%s\"" my-http-proxy)
      (message "No proxy")))

  (defun proxy-http-enable ()
    "Set http/https proxy."
    (interactive)
    (setq url-proxy-services `(("http" . ,my-http-proxy)
                               ("https" . ,my-http-proxy)))
    (proxy-http-show))

  (defun proxy-http-disable ()
    "Unset http/https proxy."
    (interactive)
    (setq url-proxy-services nil)
    (proxy-http-show))

  (defun proxy-http-toggle ()
    "Toggle http/https proxy."
    (interactive)
    (if url-proxy-services
        (proxy-http-disable)
      (proxy-http-enable)))
#+end_src
